### PR TITLE
Sylius 1.12 Update

### PR DESCRIPTION
**Pull request by DawidFrankiewicz**
| Q               | A
| --------------- | -----
| Branch?         | Sylius 1.12 or master 
| Bug fix?        | yes
| New feature?    | yes
| BC breaks?      | yes
| Deprecations?   | yes
| License         | MIT

## Description

Updated Bootstrap Theme to make it work with Sylius 1.12, improved UI without changing it and added missing UI elements that were added in Sylius 1.12, list of changes:

- Updated the readme file to reflect the new installation process
- Fixed bugs that appeard after moving to Sylius 1.12
- Changed deprecated code
- Fixed UI bugs: added missing spacings, improved mobile views.
- Added new UI elements that were added with Sylius 1.12

### CODE REVIEW

**Comment by DawidFrankiewicz** [comment]
Any updates? I would be thankful if someone could review the changes soon.

**Comment by senghe** [comment]
Hey @oallain, is there any possibility to check this and merge? :pray:

**Comment by oallain** [comment]
I review it asap.

**Review by oallain — APPROVED** [review]

**Comment by oallain** [comment]
Hello @DawidFrankiewicz 

I couldn't find you on Slack Sylius so I'm leaving you a message here hoping you read it.  
I wanted to thank you for all the work you have done, thanks to that, this plugin lives again.

Regards,
Olivier

**Pull request merged**
